multi_engine:
  target: local
  outputs:
    local:
      type: duckdb
      schema: dev
      threads: 3
      path: "local.db" #cannot have same name as motherduck db (ie. dbt.db if dbt database exists and attaching all)
      attach:
      - path: 'md:sample_data'
      - path: postgresql://{{env_var('SUPABASE_DB_USER')}}:{{env_var('SUPABASE_DB_PASSWORD')}}@{{env_var('SUPABASE_DB_HOST')}}:{{env_var('SUPABASE_DB_PORT')}}/postgres
        type: postgres
      extensions:
        - httpfs
        - parquet
        - aws
        - postgres
      secrets:
        - type: s3
          region: us-east-2
          # key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
          # secret: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
      on-run-start:
        - "INSTALL postgres; LOAD postgres;"
      on-run-end:
        - "DETACH ALL;"
    prod:
      type: duckdb
      path: "prod.db" 
    athena:
      type: athena
      s3_staging_dir: s3://.../query-results/dbt/
      s3_data_dir: s3://.../dbt/
      s3_data_naming: schema_table
      s3_tmp_table_dir: s3://../tmp/
      region_name: us-west-1
      schema: dbt 
      database: awsdatacatalog
      threads: 3
      num_retries: 1
      aws_profile_name: default
      seed_s3_upload_args:
        ACL: bucket-owner-full-control
