gateways:
  local:
    connection:
      type: duckdb
      catalogs:
        sqlmesh:
          # type: duckdb
          # path: 'db.db'
          type: motherduck
          path: 'md:sqlmesh'
        sample_data:
          type: motherduck
          path: 'md:sample_data'
          read_only: True
        postgres:
          type: postgres
          path: 'dbname=postgres user={{ env_var("SUPABASE_DB_USER") }} password={{ env_var("SUPABASE_DB_PASSWORD") }} host={{ env_var("SUPABASE_DB_HOST") }} port={{ env_var("SUPABASE_DB_PORT") }}'
          read_only: true
        epehemeral: ":memory:"
      register_comments: True
      pre_ping: False
      pretty_sql: True
      extensions:
        - motherduck 
        - httpfs
        - postgres
    state_connection:
      type: postgres
      user: {{ env_var('SUPABASE_DB_USER') }}
      port: {{ env_var('SUPABASE_DB_PORT') }}
      host: {{ env_var('SUPABASE_DB_HOST') }}
      password: {{ env_var('SUPABASE_DB_PASSWORD') }}
      database: postgres 
  md:
    connection:
      type: motherduck
      token: {{ env_var('motherduck_token') }}
      catalogs:
        prod:
          type: motherduck
          path: 'md:prod'
        sample_data:
          type: motherduck
          path: 'md:sample_data'
          read_only: True
        memory: ":memory:"

default_gateway: local

model_defaults:
  dialect: duckdb

ignore_patterns:
  - "generator"