gateways:
  duckdb:
    connection:
      type: duckdb
      catalogs:
        persistent: "db.db"
        memory: ":memory:"
      # concurrent_tasks: 1
      # register_comments: True
      # pre_ping: False
      # pretty_sql: False
      # catalogs:
      # extensions:
      # connector_config:
      # token:
    state_connection:
      type: postgres
      user: {{ env_var('SUPABASE_DB_USER') }}
      port: {{ env_var('SUPABASE_DB_PORT') }}
      host: {{ env_var('SUPABASE_DB_HOST') }}
      password: {{ env_var('SUPABASE_DB_PASSWORD') }}
      database: postgres
  motherduck:
    connection:
      type: motherduck
      catalogs:
        persistent: "md:"
        ephemeral: ":memory:"
      token: {{ env_var('MOTHERDUCK_TOKEN') }}

default_gateway: duckdb

model_defaults:
  dialect: duckdb
  start: 2025-03-10
