gateways:
  local:
    connection:
      type: duckdb
      catalogs:
        persistent: "db.db"
        memory: ":memory:"
        md:
          type: motherduck
          read_only: True
          token: {{ env_var('motherduck_token') }}
          path: 'sample_data'
      register_comments: True
      pre_ping: False
      pretty_sql: True
      extensions:
        - motherduck 
        - httpfs
    state_connection:
      type: postgres
      user: {{ env_var('SUPABASE_DB_USER') }}
      port: {{ env_var('SUPABASE_DB_PORT') }}
      host: {{ env_var('SUPABASE_DB_HOST') }}
      password: {{ env_var('SUPABASE_DB_PASSWORD') }}
      database: postgres

  md:
    connection:
      type: motherduck
      token: {{ env_var('motherduck_token') }}
      database: "test"
  md_source:
    connection:
      type: motherduck
      token: {{ env_var('motherduck_token') }}
      database: "sample_data"
      # catalogs:
      #   sample_data: "md:"
      #   memory: ":memory:"

default_gateway: local 

model_defaults:
  dialect: duckdb
  start: 2025-03-10
