[project]
name = "test-sqlmesh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg2-binary>=2.9.10",
    "sqlmesh[athena,duckdb,postgres,web]>=0.164.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
